const mongoose=require('mongoose');
const rideSchema=new mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true
    },
    captain:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Captain',
        
    },
    pickup:{
        type:String,
        required:true
    },
    destination:{
        type:String,
        required:true
    },
    fair:{
        type:Number,
        required:true
    },
    ride_status:{
        type:String,
        enum:["pending","accepted","ongoing","completed","cancelled"],
        default:"pending"
    },
    distance:{
        type:Number
    },
    duration:{
        type:String
    },
    order_id:{
        type:Number
    },
    payment_id:{
        type:Number
    },
    signature:{
        type:String
    },
    otp:{
        type:String,
        required:true,
        select:false
    },
    captain_payment:{
        type:Number
    },
    date:{
        type:Date
    }
})
const rideModel=mongoose.model('Ride',rideSchema)
module.exports=rideModel;